package ie.tcd.scss.busnotifier.domain;

import jakarta.persistence.*;
import lombok.Data;

import java.util.List;

@Entity
@Data
public class BrowserEndpoint {

    /**
     * Web Push vendor URL for this browser endpoint.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Integer id;

    @Column
    public String endpoint;

    /**
     * VAPID public key generated by the device's browser.
     * <a href="https://blog.mozilla.org/services/2016/04/04/using-vapid-with-webpush/">Described more in depth here </a>
     */
    @Column
    public String userPublicKey;

    /**
     * Produced by user's browser
     **/
    @Column
    public String userAuth;

    /**
     * A description of the device on which the subscription was made. This is actually synonymous
     * with a "browser" in this case, as the endpoint is scoped to a browser.
     */
    @Column
    public String description;

    /**
     * The user that made this browser endpoint
     */
    @ManyToOne
    public User user;

    @ManyToMany(mappedBy = "browserEndpoints")
    public List<DublinBusSubscription> dublinBusSubscriptions;
}
