services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: spring-boot
      POSTGRES_PASSWORD: spring-boot
      POSTGRES_DB: bus_notifier
    volumes:
      - ./transposed:/transposed
