logging.level.org.springframework.web: TRACE
spring.main.lazy-initialization: true
spring.datasource.url: jdbc:postgresql://localhost:54321/bus_notifier
spring.datasource.username: spring-boot
spring.datasource.password: spring-boot
hibernate.hbm2ddl.schema_filter_provider: ie.tcd.scss.busnotifier.config.Provider
spring.jpa.properties.hibernate.hbm2ddl.schema_filter_provider: ie.tcd.scss.busnotifier.config.Provider
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.database: postgresql